// Integrator (v1.2 gate C, plan checker #2). Writes the frozen v1.1 identity golden set tests/fixtures/identity-v11/:
// the 4 facility seeds/players/risk of tests/fixtures/layouts (FIXTURES in tools/gen-cli.ts at gate C) plus the hub,
// generated by the generator as it was at gate C (HEAD before the v1.2 contract) at the config/balance/level.json
// tuning. tests/fixtures/layouts is NOT touched (other tests hard-code it).
//
// E1's tests/level/identity.test.ts compares the v1.2 generator (no theme, no modifiers) against this set: read
// index.json, regenerate each entry with generateFacility({seed, players, risk}, index.tuning) (or generateHub()), and
// compare by (kind, x, z, data) with the van exceptions from the plan check (#2).
//
//   node tools/make-identity-fixtures.ts                 write the set (refuses to overwrite an existing set)
//   node tools/make-identity-fixtures.ts --check         regenerate in memory; exit 1 on any byte difference
//   node tools/make-identity-fixtures.ts --out <dir>     write a fresh copy elsewhere (diffing)
//   --force                                              overwrite (never after gate C: the set is a frozen reference)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import type { LevelLayout } from '../packages/shared/src/layout.ts';
import { GEN_VERSION } from '../packages/shared/src/layout.ts';
import { generateFacility, generateHub, validateLayout } from '../packages/shared/src/procgen/index.ts';
import type { LevelTuning } from '../packages/shared/src/procgen/index.ts';
import { loadTuning } from './gen-cli.ts';

const ROOT = resolve(import.meta.dirname, '..');
export const IDENTITY_DIR = resolve(ROOT, 'tests/fixtures/identity-v11');

/** frozen copy of tools/gen-cli.ts FIXTURES at gate C (same seeds/players/risk as tests/fixtures/layouts) */
export const IDENTITY_SET: readonly { file: string; seed: string; players: number; risk: number }[] = [
  { file: 'facility_s1_p2.json', seed: 's1', players: 2, risk: 1 },
  { file: 'facility_s2_p4.json', seed: 's2', players: 4, risk: 1 },
  { file: 'facility_s3_p6.json', seed: 's3', players: 6, risk: 1 },
  { file: 'facility_s4_p4_risk2.json', seed: 's4', players: 4, risk: 2 },
];

export interface IdentityIndex {
  v: 1;
  note: string;
  /** git HEAD the set was generated from (informational) */
  head: string;
  genVersion: number;
  /** resolved generator tuning used (config/balance/level.json at gate C over the defaults) */
  tuning: LevelTuning;
  entries: { file: string; kind: 'facility' | 'hub'; seed: string; players?: number; risk?: number; hash: string; items: number; spaces: number; doors: number }[];
}

function build(tuning: LevelTuning): { files: Map<string, string>; entries: IdentityIndex['entries'] } {
  const files = new Map<string, string>();
  const entries: IdentityIndex['entries'] = [];
  const put = (file: string, L: LevelLayout, e: Omit<IdentityIndex['entries'][number], 'file' | 'hash' | 'items' | 'spaces' | 'doors'>) => {
    const errs = validateLayout(L).errors;
    if (errs.length) throw new Error(`${file}: invalid layout: ${errs.join('; ')}`);
    files.set(file, JSON.stringify(L));
    entries.push({ file, ...e, hash: L.hash, items: L.items.length, spaces: L.spaces.length, doors: L.doors.length });
  };
  for (const f of IDENTITY_SET) {
    put(f.file, generateFacility({ seed: f.seed, players: f.players, risk: f.risk }, tuning), { kind: 'facility', seed: f.seed, players: f.players, risk: f.risk });
  }
  put('hub.json', generateHub(), { kind: 'hub', seed: 'hub' });
  return { files, entries };
}

function gitHead(): string {
  try { return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); } catch { return 'unknown'; }
}

function main(): void {
  const args = process.argv.slice(2);
  const has = (k: string) => args.includes(`--${k}`);
  const outIdx = args.indexOf('--out');
  const dir = outIdx >= 0 && args[outIdx + 1] ? resolve(args[outIdx + 1]) : IDENTITY_DIR;
  if (has('check')) {
    const idx = JSON.parse(readFileSync(resolve(IDENTITY_DIR, 'index.json'), 'utf8')) as IdentityIndex;
    const { files } = build(idx.tuning);
    let bad = 0;
    for (const [file, json] of files) {
      const same = readFileSync(resolve(IDENTITY_DIR, file), 'utf8') === json;
      if (!same) bad++;
      console.log(`${same ? 'same   ' : 'CHANGED'} ${file}`);
    }
    const tuningNow = JSON.stringify(loadTuning()) === JSON.stringify(idx.tuning);
    console.log(`config/balance/level.json tuning ${tuningNow ? 'unchanged' : 'CHANGED'} since gate C`);
    if (bad) process.exitCode = 1;
    return;
  }
  if (dir === IDENTITY_DIR && existsSync(resolve(dir, 'index.json')) && !has('force')) {
    console.error(`${dir} already exists: it is the frozen v1.1 reference (use --out <dir> for a fresh copy)`);
    process.exitCode = 1;
    return;
  }
  const tuning = loadTuning();
  const { files, entries } = build(tuning);
  mkdirSync(dir, { recursive: true });
  for (const [file, json] of files) writeFileSync(resolve(dir, file), json);
  const index: IdentityIndex = {
    v: 1,
    note: 'Frozen v1.1 identity reference (plan checker #2). Generated once at gate C by tools/make-identity-fixtures.ts; never regenerate. tests/fixtures/layouts is separate.',
    head: gitHead(), genVersion: GEN_VERSION, tuning, entries,
  };
  writeFileSync(resolve(dir, 'index.json'), `${JSON.stringify(index, null, 2)}\n`);
  for (const e of entries) console.log(`${e.file} ${e.hash} items=${e.items} spaces=${e.spaces} doors=${e.doors}`);
  console.log(`wrote ${entries.length} layouts + index.json to ${dir}`);
}

if (import.meta.filename === resolve(process.argv[1] ?? '')) main();
